id = "gren"
name = "Gren"
version = "0.1.0"
schema_version = 1
authors = ["Johan Alkstål <github@johanalkstal.com>"]
description = "Syntax highlighting for Gren"
repository = "https://github.com/johanalkstal/gren-lang-extension"

[grammars.gren]
repository = "https://github.com/MaeBrooks/tree-sitter-gren"
commit = "c06e272341363c5d8e19ac34bc7c56258a37e71b"
